#!/usr/bin/env node
/**
 * Generates src/version-info.js with a deterministic mystical version name
 * seeded from the git short hash. Same commit always produces the same name.
 */
const { execFileSync } = require("child_process");
const fs = require("fs");
const path = require("path");

// ─── Word Lists (tarot/mystical theme) ───

const ADJECTIVES = [
  "Arcane", "Astral", "Celestial", "Crimson", "Crystal",
  "Dreaming", "Elder", "Ember", "Enchanted", "Ethereal",
  "Fading", "Flickering", "Forgotten", "Gilded", "Golden",
  "Hallowed", "Hidden", "Hollow", "Illuminated", "Ivory",
  "Lunar", "Midnight", "Mystic", "Obsidian", "Opal",
  "Phantom", "Radiant", "Sacred", "Sapphire", "Shadowed",
  "Silent", "Silver", "Spectral", "Starlit", "Sunken",
  "Twilight", "Veiled", "Violet", "Wandering", "Whispering",
];

const NOUNS = [
  "Amulet", "Arcana", "Bloom", "Candle", "Chalice",
  "Chronicle", "Cipher", "Dawn", "Eclipse", "Elixir",
  "Flame", "Glyph", "Grove", "Lantern", "Loom",
  "Mirror", "Moth", "Oracle", "Passage", "Petal",
  "Prism", "Quill", "Relic", "Rite", "Rune",
  "Sanctum", "Scroll", "Seal", "Shard", "Sigil",
  "Solstice", "Spell", "Talisman", "Tapestry", "Tempest",
  "Threshold", "Token", "Veil", "Vessel", "Vision",
];

// ─── Hash → Index ───

function hashToIndex(hash, listLength) {
  let n = 0;
  for (let i = 0; i < hash.length; i++) {
    n = (n * 31 + hash.charCodeAt(i)) >>> 0;
  }
  return n % listLength;
}

// ─── Main ───

let shortHash;
try {
  shortHash = execFileSync("git", ["rev-parse", "--short", "HEAD"], { encoding: "utf-8" }).trim();
} catch {
  shortHash = "dev";
}

const adj = ADJECTIVES[hashToIndex(shortHash, ADJECTIVES.length)];
const noun = NOUNS[hashToIndex(shortHash + "n", NOUNS.length)];
const versionName = `${adj} ${noun}`;

const outPath = path.join(__dirname, "..", "src", "version-info.js");
const content = `// Auto-generated by scripts/version.js — do not edit
const VERSION_HASH = ${JSON.stringify(shortHash)};
const VERSION_NAME = ${JSON.stringify(versionName)};
export { VERSION_HASH, VERSION_NAME };
`;

fs.writeFileSync(outPath, content);
console.log(`Version: ${versionName} · ${shortHash}`);
