#!/usr/bin/env node
// Writes worker/version-info.js with git metadata baked in at deploy time.
// Mirrors scripts/version.js but targets the Worker bundle.

const { execFileSync } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");

function git(args) {
  try {
    return execFileSync("git", args, { encoding: "utf8" }).trim();
  } catch {
    return "";
  }
}

const hash = git(["rev-parse", "--short", "HEAD"]) || "dev";
const branch = git(["rev-parse", "--abbrev-ref", "HEAD"]) || "unknown";
let dirty = false;
try {
  execFileSync("git", ["diff", "--quiet"]);
} catch {
  dirty = true;
}

const built = new Date().toISOString();

const outPath = path.join(__dirname, "..", "worker", "version-info.js");
const content = `// Auto-generated by scripts/worker-version.js — do not edit
export const HASH = ${JSON.stringify(hash)};
export const BRANCH = ${JSON.stringify(branch)};
export const DIRTY = ${JSON.stringify(dirty)};
export const BUILT = ${JSON.stringify(built)};
`;

fs.writeFileSync(outPath, content);
console.log(`Worker version: ${hash} (${branch}${dirty ? ", dirty" : ""})`);
